const API='/api';let state={token:localStorage.getItem('cf_token'),user:JSON.parse(localStorage.getItem('cf_user')||'null'),page:'dashboard',doctors:[],appointments:[],stats:{}};
const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(state.token)h.Authorization=`Bearer ${state.token}`;const r=await fetch(API+path,{...opt,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Something went wrong');return d}
function toast(m){const t=$('#toast');t.innerHTML=`<div class="notice toast">${esc(m)}</div>`;setTimeout(()=>t.innerHTML='',3200)}
function shell(content){return `<div class="shell"><header class="topbar"><div class="brand"><div class="brandmark">✚</div>CareFlow</div><nav class="nav">${['dashboard','appointments'].map(p=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${p==='dashboard'?'Overview':'Appointments'}</button>`).join('')}${state.user.role==='patient'?'<button class="'+(state.page==='doctors'?'active':'')+'" onclick="go(\'doctors\')">Find Doctor</button>':''}${state.user.role==='admin'?'<button class="'+(state.page==='admin'?'active':'')+'" onclick="go(\'admin\')">Admin</button>':''}<button class="ghost" onclick="logout()">Sign out</button></nav></header>${content}<div class="footer">CareFlow • Healthcare Appointment & Follow-up Manager</div></div>`}
function auth(){return `<div class="auth"><div class="authbox"><div class="authvisual"><div class="eyebrow">Compassionate care, simplified</div><h1>Appointments that feel human.</h1><p>Book, prepare, follow up and stay connected — in one calm healthcare workspace.</p><div class="pulse"><i></i><span>AI-assisted visit preparation</span></div><div class="pulse"><i></i><span>Reliable reminders & notifications</span></div><div class="pulse"><i></i><span>Calendar-ready appointments</span></div></div><div class="authform"><div class="eyebrow">Welcome to CareFlow</div><h2 id="authTitle">Sign in</h2><div id="authBody"></div></div></div></div>`}
function authBody(mode='login'){const register=mode==='register';$('#authTitle').textContent=register?'Create patient account':'Sign in';$('#authBody').innerHTML=`<form class="form" onsubmit="submitAuth(event,'${register?'register':'login'}')">${register?'<input name="name" placeholder="Full name" required>':''}<input name="email" type="email" placeholder="Email address" required><input name="password" type="password" placeholder="Password" minlength="6" required><button class="btn">${register?'Create account':'Continue'}</button></form><p class="muted">${register?'Already have an account?':'New to CareFlow?'} <button class="switch" onclick="authBody('${register?'login':'register'}')">${register?'Sign in':'Create account'}</button></p><div class="notice"><b>Demo accounts</b><br>Patient: patient@careflow.local / password123<br>Doctor: doctor@careflow.local / password123<br>Admin: admin@careflow.local / password123</div>`}
async function submitAuth(e,type){e.preventDefault();const f=new FormData(e.target);try{const d=await api(`/auth/${type}`,{method:'POST',body:JSON.stringify(Object.fromEntries(f))});state.token=d.token;state.user=d.user;localStorage.setItem('cf_token',state.token);localStorage.setItem('cf_user',JSON.stringify(state.user));render()}catch(e){toast(e.message)}}
function logout(){localStorage.clear();state.token=null;state.user=null;render()}
async function load(){if(!state.user)return;state.stats=await api('/dashboard');state.appointments=await api('/appointments');if(state.user.role==='patient'||state.user.role==='admin')state.doctors=await api('/doctors')}
async function go(p){state.page=p;await render()}
function dashboard(){const s=state.stats;const labels=state.user.role==='patient'?[['total','Total visits','📋'],['upcoming','Upcoming','🗓️'],['completed','Completed','✓'],['reminders','Reminders','⏰']]:state.user.role==='doctor'?[['today','Today','🩺'],['upcoming','Upcoming','🗓️'],['completed','Completed','✓'],['highUrgency','High urgency','⚠️']]:[['patients','Patients','👥'],['doctors','Doctors','🩺'],['appointments','Appointments','🗓️'],['cancelled','Cancelled','↩️']];return `<main class="page"><section class="hero"><div><div class="eyebrow">Good to see you, ${esc(state.user.name.split(' ')[0])}</div><h1>Your care, beautifully organized.</h1><p>One place for appointments, symptom preparation, visit summaries and timely follow-up.</p><button class="btn" onclick="go('${state.user.role==='patient'?'doctors':'appointments'}')">${state.user.role==='patient'?'Book an appointment':'View appointments'} →</button></div><div class="hero-card"><div class="eyebrow">CareFlow pulse</div><h3>Stay one step ahead</h3><p class="muted">Your dashboard updates from the same appointment and reminder system used by your care team.</p><div class="pulse"><i></i><span>Secure role-based workspace</span></div><div class="pulse"><i></i><span>Smart conflict prevention</span></div></div></section><div class="grid">${labels.map(x=>`<div class="card"><div>${x[2]}</div><div class="stat">${s[x[0]]??0}</div><div class="muted">${x[1]}</div></div>`).join('')}</div><div class="section-title"><div><div class="eyebrow">Recent activity</div><h2>Appointments</h2></div><button class="ghost" onclick="go('appointments')">See all →</button></div>${appointmentTable(state.appointments.slice(-5).reverse())}</main>`}
function appointmentTable(rows){if(!rows.length)return '<div class="card empty">No appointments yet.</div>';return `<div class="card"><table class="table"><thead><tr><th>Date</th><th>${state.user.role==='patient'?'Doctor':'Patient'}</th><th>Time</th><th>Urgency</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(a=>`<tr><td>${esc(a.appointment_date)}</td><td>${esc(a.doctor_name||a.patient_name||'')}</td><td>${esc(a.start_time)}</td><td><span class="status ${(a.ai_urgency||'Low').toLowerCase()}">${esc(a.ai_urgency||'Low')}</span></td><td><span class="status ${a.status}">${esc(a.status)}</span></td><td>${a.ai_summary?`<button class="ghost" onclick="showSummary('${a.id}')">AI summary</button>`:''} ${a.patient_summary?`<button class="ghost" onclick="showVisitSummary('${a.id}')">Visit summary</button>`:''} ${a.status==='booked'?`<button class="ghost" onclick="cancelAppt('${a.id}')">Cancel</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
function doctors(){return `<main class="page"><div class="section-title"><div><div class="eyebrow">Find your clinician</div><h2>Available doctors</h2></div><span class="muted">Search by specialty</span></div><div class="doctors">${state.doctors.map(d=>`<div class="card doctor"><div class="row"><div class="avatar">${esc(d.name.replace('Dr. ','').split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><span class="tag">${esc(d.specialization)}</span></div><h3>${esc(d.name)}</h3><p class="muted">${esc(d.bio)}</p><small class="muted">${d.working_start} – ${d.working_end} • ${d.slot_duration} min slots</small><br><button class="btn" style="margin-top:15px" onclick="book('${d.id}')">Choose time</button></div>`).join('')}</div></main>`}
async function book(id){const d=state.doctors.find(x=>x.id===id);const today=new Date().toISOString().slice(0,10);openModal(`<h2>Book with ${esc(d.name)}</h2><form class="form" onsubmit="confirmBooking(event,'${id}')"><label>Date<input id="bookDate" type="date" min="${today}" value="${today}" onchange="refreshSlots('${id}')" required></label><div><b>Available times</b><div id="slots" class="slots" style="margin-top:9px"></div></div><label>Symptoms / reason for visit<textarea name="symptoms" rows="4" placeholder="Tell the doctor what you are experiencing..."></textarea></label><div class="notice">AI will prepare a screening summary for the doctor. It is not a diagnosis.</div><input type="hidden" name="startTime" id="chosenSlot"><button class="btn">Confirm appointment</button></form>`);refreshSlots(id)}
async function refreshSlots(id){const date=$('#bookDate').value;const a=await api(`/doctors/${id}/slots?date=${date}`);$('#slots').innerHTML=a.length?a.map(x=>`<button type="button" class="slot" ${x.available?'':'disabled'} onclick="chooseSlot('${x.start}', '${id}', '${date}')">${x.start}</button>`).join(''):'<span class="muted">Doctor unavailable on this date.</span>'}
async function chooseSlot(x, doctorId, date){
  try {
    await api('/appointments/hold', { method: 'POST', body: JSON.stringify({ doctorId, date, startTime: x }) });
    $('#chosenSlot').value=x;
    document.querySelectorAll('.slot').forEach(b=>b.style.outline=b.textContent===x?'3px solid #f5a9c5':'none');
    toast('Slot held for 5 minutes. Please complete the form.');
  } catch(e) {
    toast(e.message || 'This slot was just taken by someone else.');
    refreshSlots(doctorId);
  }
}
async function confirmBooking(e,id){e.preventDefault();const f=new FormData(e.target);if(!f.get('startTime'))return toast('Please choose an available time.');const btn=e.target.querySelector('button.btn');btn.disabled=true;btn.textContent='Booking…';try{const a=await api('/appointments',{method:'POST',body:JSON.stringify({doctorId:id,date:$('#bookDate').value,startTime:f.get('startTime'),symptoms:f.get('symptoms')})});closeModal();await render();toast('Appointment booked! Your AI symptom summary is ready.');setTimeout(()=>showSummary(a.id),150)}catch(e){btn.disabled=false;btn.textContent='Confirm appointment';toast(e.message)}}
function appointments(){return `<main class="page"><div class="section-title"><div><div class="eyebrow">Your timeline</div><h2>Appointments</h2></div>${state.user.role==='patient'?'<button class="btn" onclick="go(\'doctors\')">+ New appointment</button>':''}</div>${appointmentTable(state.appointments.slice().reverse())}${state.user.role==='doctor'?`<div class="section-title"><div><div class="eyebrow">Doctor workspace</div><h2>Complete a visit</h2></div></div><div class="card"><p class="muted">Choose a booked appointment to enter notes and a prescription.</p>${state.appointments.filter(a=>a.status==='booked').map(a=>`<div class="row" style="padding:12px 0;border-bottom:1px solid var(--line)"><span><b>${esc(a.patient_name)}</b><br><small>${a.appointment_date} • ${a.start_time} • <span class="status ${(a.ai_urgency||'Low').toLowerCase()}">${a.ai_urgency}</span></small></span><button class="btn" onclick="visit('${a.id}')">Open visit</button></div>`).join('')||'<div class="empty">No booked visits.</div>'}</div>`:''}</main>`}
function visit(id){openModal(`<h2>Post-visit notes</h2><form class="form" onsubmit="saveVisit(event,'${id}')"><label>Clinical notes<textarea name="notes" rows="6" required placeholder="Enter concise visit notes..."></textarea></label><label>Prescription / frequency<textarea name="prescription" rows="4" placeholder="Example: Medicine A — twice daily after meals"></textarea></label><div class="notice">CareFlow will generate a patient-friendly summary and activate medication reminders when a prescription is entered.</div><button class="btn">Complete visit</button></form>`)}
async function saveVisit(e,id){e.preventDefault();const f=new FormData(e.target);try{const d=await api(`/appointments/${id}/visit`,{method:'POST',body:JSON.stringify(Object.fromEntries(f))});closeModal();toast('Visit completed and patient summary generated.');await render()}catch(e){toast(e.message)}}
async function cancelAppt(id){if(!confirm('Cancel this appointment?'))return;try{await api(`/appointments/${id}/cancel`,{method:'PATCH',body:JSON.stringify({reason:'Cancelled by user'})});toast('Appointment cancelled');await render()}catch(e){toast(e.message)}}
function admin(){return `<main class="page"><div class="section-title"><div><div class="eyebrow">Administration</div><h2>Clinic operations</h2></div></div><div class="split"><div class="card"><h3>Add doctor</h3><form class="form" onsubmit="addDoctor(event)"><input name="name" placeholder="Doctor name" required><input name="email" type="email" placeholder="Email" required><input name="password" placeholder="Temporary password" value="password123"><input name="specialization" placeholder="Specialisation" required><input name="workingStart" value="09:00"><input name="workingEnd" value="17:00"><input name="slotDuration" type="number" value="30" min="10"><textarea name="bio" placeholder="Short bio"></textarea><button class="btn">Create doctor</button></form></div><div class="card"><h3>Doctor leave</h3><p class="muted">Use the doctor profile ID shown below.</p>${state.doctors.length?state.doctors.map(d=>`<div class="row" style="padding:10px 0;border-bottom:1px solid var(--line)"><span><b>${esc(d.name)}</b><br><small>${d.specialization} • ID ${d.id}</small></span><button class="btn secondary" onclick="leave('${d.id}')">Mark leave</button></div>`).join(''):'<p class="muted">Log in as admin and refresh to load profiles.</p>'}</div></div></main>`}
async function addDoctor(e){e.preventDefault();try{await api('/admin/doctors',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('Doctor created');await render()}catch(e){toast(e.message)}}
function leave(id){openModal(`<h2>Mark doctor leave</h2><form class="form" onsubmit="saveLeave(event,'${id}')"><input name="date" type="date" min="${new Date().toISOString().slice(0,10)}" required><input name="reason" value="Doctor unavailable"><button class="btn">Confirm leave</button></form>`)}
async function saveLeave(e,id){e.preventDefault();try{const r=await api(`/admin/doctors/${id}/leave`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});closeModal();toast(`${r.message}. ${r.affectedAppointments} affected appointment(s).`);await render()}catch(e){toast(e.message)}}
function openModal(x){const m=document.createElement('div');m.className='modal';m.id='modal';m.innerHTML=`<div class="modalbox"><div class="row"><span></span><button class="ghost" onclick="closeModal()">✕</button></div>${x}</div>`;document.body.appendChild(m)}function closeModal(){$('#modal')?.remove()}
async function render(){if(!state.user){$('#app').innerHTML=auth();authBody();return}try{await load();const content=state.page==='doctors'?doctors():state.page==='appointments'?appointments():state.page==='admin'?admin():dashboard();$('#app').innerHTML=shell(content)}catch(e){if(e.message.includes('Login'))logout();else toast(e.message)}}
render();

function showSummary(id){const a=state.appointments.find(x=>x.id===id);if(!a)return;let x={};try{x=JSON.parse(a.ai_summary||'{}')}catch{}openModal(`<h2>AI Symptom Summary</h2><div class="card"><p><b>Urgency:</b> <span class="status ${(x.urgency||a.ai_urgency||'Low').toLowerCase()}">${esc(x.urgency||a.ai_urgency||'Low')}</span></p><p><b>Summary</b><br>${esc(x.summary||'No summary available.')}</p><p><b>Questions for the doctor</b></p><ul>${(x.questions||[]).map(q=>`<li>${esc(q)}</li>`).join('')}</ul></div><p class="muted">This is an AI-assisted screening summary, not a diagnosis.</p>`)}
function showVisitSummary(id){const a=state.appointments.find(x=>x.id===id);if(!a)return;let x={};try{x=JSON.parse(a.patient_summary||'{}')}catch{}openModal(`<h2>Post-Visit Summary</h2><div class="card"><p><b>Summary</b><br>${esc(x.summary||'No summary available.')}</p><p><b>Medication schedule</b><br>${esc(x.medicationSchedule||a.prescription||'None recorded')}</p><p><b>Follow-up</b><br>${esc(x.followUp||'Follow your clinician’s instructions.')}</p></div>`)}
